Change algorithm for SP displayname & refactor algorithm for organization name
OpenConext/OpenConext-engineblock pull request #1042
Opened 2020-12-19 11:03 UTC by Badlapje

As one of the [feedback items]([url](https://wiki.surfnet.nl/display/coininfra/Bevindingen+december+2020)) it was requested that we change the algorithm for the SP displayname to:
1. displayname in preferred locale
2. name in preferred locale
3. displayname in english
4. name in english
5. entityID (should never happen as an english name is mandatory)

I took advantage of the opportunity to refactor the organizationName method as well.  This to address the remarks in the previous PRs that dealt with this method: [one by me](https://github.com/OpenConext/OpenConext-engineblock/pull/980#discussion_r529379926) and [one by martin](https://github.com/OpenConext/OpenConext-engineblock/pull/1022/files#r543128672)

2020-12-23 07:56 UTC, MKodde requested changes
I approve of your changes! In my review you will see what I dislike about them, but overall I think this is a step forward!

To make this change complete, I'd love to see tests added to `ServiceProviderTest` Maybe you can concoctionate a data provider that seeds service providers with different sets of names/display titles and so forth, verifying the correct `getDisplayname` and `getOrganizationName` behavior.

If you  need help, or some pointers, feel free to slack me. Or create a task for me to create the tests!

2020-12-23 07:56 UTC, MKodde commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +     *
:heart:, please add a link to the story/task in Pivotal where this was explicitly requested. 

If there is none, consider creating it for future administration, or leave it as is. This is not a major/big requirement.

2020-12-23 07:56 UTC, MKodde commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +            $spName = !empty($this->displayNameEn) ? $this->displayNameEn : $this->nameEn;
1. Lines of code have decreased :+1: 
2. It is easier to add languages :+1: 
3. Readability was decreased significantly (in my opinion (old school developer here)) which accounts to a minor thumbs down.

But all in all the score is still :+1:

2020-12-23 07:56 UTC, MKodde commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
>       * @return string
If you type hint the preferredLocale param and add a return type, you can remove the PHPDoc annotations as they have become obsolete. 

This should also test the calling code. If it misbehaves or passes incorrect values we should start see errors :fearful:

2020-12-23 07:56 UTC, MKodde commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +     * @return string
**Nitpick**
Insignificant PHPDoc can be removed from the code base

2020-12-23 10:13 UTC, Badlapje commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +     *
I added a link to the "bevindingen" where this was requested (it actually was there but i messed up the markdown).  Is that ok or would you rather have a pivotal task (i didn't add any of the bevindingen i fixed to the pivotal tracker)?

2020-12-23 10:17 UTC, Badlapje commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +            $spName = !empty($this->displayNameEn) ? $this->displayNameEn : $this->nameEn;
I could add some comments above $spName to increase readability?  Something like this:

```
// use $this->displayName for the locale if possible
// use $this->name for the locale if the displayname is empty
```

2020-12-23 10:18 UTC, Badlapje commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +            $spName = !empty($this->displayNameEn) ? $this->displayNameEn : $this->nameEn;
in fact i can also get rid of the $preferredLocale !== 'en' on line 354 as that should never be empty at that point.

2020-12-23 10:20 UTC, Badlapje commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
>       * @return string
Good one :-)  Done!

2020-12-23 10:21 UTC, Badlapje commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
>       * @return string
Also removed one unused import

2020-12-23 10:21 UTC, Badlapje commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +     * @return string
💯

2020-12-23 10:33 UTC, MKodde commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +     *
A link to whatever Pivotal ticket is fine with me. That way we can correspond on that story in the future. An probably pull back memories from this development effort if need be. As in, we can blame someone for actions taken here ;P

Nah just kiddin', it's protocol to try and cross link stories with PR's. Just to more easily check the technical outcome of a functional requirement/bugreport/wossname

2020-12-23 10:39 UTC, MKodde commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +            $spName = !empty($this->displayNameEn) ? $this->displayNameEn : $this->nameEn;
I'm not a big advocate to add comments to make code more readable/understandable. In my opinion code should speak for itself. When code is optimized by using language constructions like inline conditional statements and so forth, that decrease readability. I will advocate to not using them. But as mentioned. I'm somewhat oldschool, and your code is far from 'unreadable'. So I think your suggestion to add comments should not be implemented.

Using the empty function might also be a bit of a visual annoyance to me. I prefer using `=== ''` My annoance is mainly due to the negation that is required to test if something is empty or not. And PHP is very unpredictable in what is considered empty. For example NULL might be considered empty, but is it really? 

That's why I advocate the unit test to test the bulletproofness of this code (if that sentence makes sense at all) For by examining this code I'm not sure all PHP quirks are covered :hand_over_mouth:

2020-12-23 10:41 UTC, MKodde commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
>       * @return string
![Exellent](https://media.giphy.com/media/8fen5LSZcHQ5O/giphy.gif)

2020-12-23 10:43 UTC, MKodde commented
Great work improving the PR. Last action is to add an unit test to verify the name retrieval methods. I'm okay with merging this for now. If you add a story/task to a still open ticket. And assign me to write the test. Or do it yourself, whatever fits your agenda best!

2020-12-23 10:43 UTC, MKodde approved these changes

2020-12-23 13:30 UTC, Badlapje commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +     *
done

2020-12-23 13:40 UTC, Badlapje commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +            $spName = !empty($this->displayNameEn) ? $this->displayNameEn : $this->nameEn;
> I'm not a big advocate to add comments to make code more readable/understandable. In my opinion code should speak for itself. When code is optimized by using language constructions like inline conditional statements and so forth, that decrease readability. I will advocate to not using them. But as mentioned. I'm somewhat old-school, and your code is far from 'unreadable'. So I think your suggestion to add comments should not be implemented.

I generally support the above, but the problem i have with this logic is that there's a subjective point as to what constitutes code that speaks for itself.  That question will be answered differently depending on who you ask.  I'd prefer writing code a beginner would understand, but then that'd exclude a lot of cool things and even design patterns.  

I tend to solve that by:
- either creating micro-methods which i can give descriptive names (works really well in JS), 
- or adding comments to clarify things which i reckon might not be clear to beginners, (generally i prefer adding too many comments over adding too few)
- or underestimating how hard something is to read and not adding comments.

> Using the empty function might also be a bit of a visual annoyance to me. I prefer using === '' My annoyance is mainly due to the negation that is required to test if something is empty or not. And add to that, that PHP is very unpredictable in what is considered empty. For example NULL might be considered empty, but is it really?

I agree on this one.  The empty function is part of the old code as well though.

2020-12-23 14:17 UTC, Badlapje commented
Added unit tests, data provider ftw!

2020-12-23 20:49 UTC, MKodde commented on tests/unit/OpenConext/EngineBlock/Metadata/Entity/ServiceProviderTest.php
> +            $sp = new ServiceProvider(
Nice work! Love your test! To improve the test slightly perhaps:

1. Add a similar test for the OrganizationName
1. A method to create the service provider, making the test more clean to look at
1. Consider changing the type definitions for the test method, preventing the optional parameters. This is a nitpick, and might be hard to prevent in this test setup. But for regular methods, this is considered bad practice.

2020-12-24 10:15 UTC, Badlapje commented on tests/unit/OpenConext/EngineBlock/Metadata/Entity/ServiceProviderTest.php
> +            $sp = new ServiceProvider(
Did one and two, but preventing optional parameters is not possible outside of just chucking in a load of useless data.  Sadly named parameters (which would prevent the optional parameters) are only available as of PHP 8

2020-12-29 10:20 UTC, MKodde commented
Hi @Badlapje thanks for you awesome work on the unit tests, I found a sneaky bug in the organization name method. In addition I might have squashed some of your commits 

![Squashed](https://media.giphy.com/media/ge3SJPKwPdZSClGEua/giphy.gif)

2020-12-29 10:24 UTC, MKodde commented on src/OpenConext/EngineBlock/Metadata/Entity/ServiceProvider.php
> +        if (($preferredLocale !== 'en' && empty($orgName)) || empty($orgName)) {
The previous setup of this if statement was causing the unit tests to fail. When requesting an non English OrgName, the condition would always succeed as preferred locale is not EN.

Previous statement was:

`if ($preferredLocale !== 'en' || empty($orgName)) {`

2020-12-29 10:49 UTC, MKodde commented
Rebased this onto parent branch who received Behat test fixes.

Merging once CI agrees with the changeset!

2020-12-29 10:49 UTC, merged

2020-12-30 09:09 UTC, Badlapje commented
> 
> Hi @Badlapje thanks for you awesome work on the unit tests, I found a sneaky bug in the organization name method. In addition I might have squashed some of your commits

nice catch!

And thx for the rebase/merge!