Add screenreader support for the wayf
OpenConext/OpenConext-engineblock pull request #1048
Opened 2020-12-27 15:20 UTC by Badlapje

SR check now that the wayf is finished revealed some more issues.  Resolved those in this PR

2020-12-30 10:00 UTC, MKodde reviewed
I liked what is saw, and had some suggestions/questions. Feel free to skip some of the nitpicks

2020-12-30 10:00 UTC, MKodde commented on theme/skeune/translations/messages.nl.php
> +    'reset'         => 'Wis de tekst in het zoekveld',
Are these agreed upon translations? 

Please add a link to the relevant story task.
And I'm making a mental note to add this translation key to the PT translation task ahead.

2020-12-30 10:00 UTC, MKodde commented on theme/base/javascripts/utility/changeAriaPressed.js
> +  element.setAttribute('aria-pressed', newValue[ariaPressed]);
Wouldn't a simple `lement.setAttribute('aria-pressed', !ariaPressed);` not work the same way, removing the need for the newValue construction?

2020-12-30 10:00 UTC, MKodde commented on theme/base/javascripts/wayf/mouseBehaviour.js
> +  const labels = document.querySelectorAll('input[aria-pressed]');
This seems unsound in a semantical way. The labels constant is populated with inputs having the `aria-pressed` attr. Maybe the inputs act as a label, in that case, maybe add a little comment that explains this.

2020-12-30 10:00 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
> +<ul class="wayf__idpList{% if cutoffPointForShowingUnfilteredIdps < idpList|length %} wayf__idpList--cutoffMet{% endif %}" aria-labelledby="{{ id }}">
For readabilities sake, consider making this a multi-line element statement.

2020-12-30 10:00 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/ctas.html.twig
> +        <span class="visually-hidden">{{ 'wayf_noaccess_request_access'|trans }}</span>
Is this best practice? Or just a trick to get another translation to be read when using a screen reader? In that case maybe mark the translation key to indicate this is a SR translation. That might aid a human translator in setting a sensible text?

If I'm missing the point completely, feel free to laugh at me and point me in the right direction ;P

2020-12-30 10:00 UTC, MKodde commented on theme/skeune/translations/messages.nl.php
> +    'wayf_noaccess_request_access'  => 'Open het formulier om toegang aan te vragen',
Again, are these translations agreed upon by the PM/PO? If this is not the case be sure to run them by them. They look sane, but you never know..

2020-12-30 10:00 UTC, MKodde commented on theme/base/javascripts/wayf/utility/switchIdpSection.js
>    }
You might be able to get rid of the `else` statement by removing the aria-hidden by default. And setting it in the conditional statement if the conditions are met. 

Always try to prevent using else statements if they can be avoided. Maybe this is not the case here as I do not know if the JS engine likes a `removeAttribute` statement if the attr is not actually present.

2021-01-03 20:53 UTC, Badlapje commented on theme/skeune/translations/messages.nl.php
> +    'reset'         => 'Wis de tekst in het zoekveld',
nope, but i changed the key to incorporate screenreader so i can add them to that list for Thijs

2021-01-03 20:57 UTC, Badlapje commented on theme/skeune/translations/messages.nl.php
> +    'wayf_noaccess_request_access'  => 'Open het formulier om toegang aan te vragen',
same answer as above ;-)

2021-01-03 20:58 UTC, Badlapje commented on theme/base/javascripts/utility/changeAriaPressed.js
> +  element.setAttribute('aria-pressed', newValue[ariaPressed]);
No, as the value is not a boolean but a string.  I tried that one first indeed, but sadly noGo :(

2021-01-03 21:00 UTC, Badlapje commented on theme/base/javascripts/wayf/mouseBehaviour.js
> +  const labels = document.querySelectorAll('input[aria-pressed]');
Nice one!  No, it's actually the checkboxes who have the aria-pressed attribute rather than the labels.  Corrected the comment & variable name.

2021-01-03 21:02 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/noAccess/ctas.html.twig
> +        <span class="visually-hidden">{{ 'wayf_noaccess_request_access'|trans }}</span>
You are spot on, so no laughing at you 🥇 

Added the key to indicate it's a SR translation.  Best practice is no separate translations for SR and visual UI, but in this case given the brevity of the button text it wouldn't be understandable for a SR-user.

2021-01-03 21:05 UTC, Badlapje commented on theme/base/javascripts/wayf/utility/switchIdpSection.js
>    }
nice one!  Done.

2021-01-03 21:11 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
> +<ul class="wayf__idpList{% if cutoffPointForShowingUnfilteredIdps < idpList|length %} wayf__idpList--cutoffMet{% endif %}" aria-labelledby="{{ id }}">
done, and set a variable for bonus points

2021-01-03 21:12 UTC, Badlapje commented
> Feel free to skip some of the nitpicks

The t's have been crossed and the i's have been dotted.  I skip no nitpicks, for the path to excellence they are!

2021-01-04 07:34 UTC, MKodde commented on theme/base/javascripts/utility/changeAriaPressed.js
> +  element.setAttribute('aria-pressed', newValue[ariaPressed]);
Ah, that kind of complicates things indeed. In that case, in an optimal situation you'd like to have a 'model/domain object/value object/thingy' that keeps a boolean state, and a view object that's tasked with rendering the domain object into something that makes sense to the browser. But lets not over complicate things here. Adding layers just to satisfy my sick separation of concerns standards is not what we are after here..

2021-01-04 07:37 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
> +<ul class="wayf__idpList{% if cutoffPointForShowingUnfilteredIdps < idpList|length %} wayf__idpList--cutoffMet{% endif %}" aria-labelledby="{{ id }}">
Nice! Makes things much more readable and somewhat more understandable. I say somewhat as the cutoff logic always has me boggled.

2021-01-04 07:49 UTC, MKodde commented on theme/base/javascripts/utility/changeAriaPressed.js
> +  element.setAttribute('aria-pressed', newValue[ariaPressed]);
Possible alternatively brainwave alert: 

You might have been able to store 0/1 on the attribute representing the boolean state. That might have been cast-able to a boolean value :man_shrugging: 

This solution is good enough for rock and roll, and thanks to the additional comment, maintainable in the future.

2021-01-04 07:53 UTC, MKodde requested changes
Thanks for the improvements. One of your changes contained an additional possible issue. See my comment below for details.

2021-01-04 07:53 UTC, MKodde commented on theme/skeune/translations/messages.pt.php
> +    'wayf_noaccess_title_screenreader_screenreader'       => 'Request access for this account',
Warning: `wayf_noaccess_title_screenreader_screenreader`, note the `screenreader_screenreader` redundancy. This is not present in the Dutch version, but is in EN and PT. Please fix this!

2021-01-04 08:07 UTC, Badlapje commented on theme/skeune/translations/messages.pt.php
> +    'wayf_noaccess_title_screenreader_screenreader'       => 'Request access for this account',
gah, fixed

2021-01-04 08:17 UTC, MKodde approved these changes
:heavy_check_mark: 

You be the judge on how you want to merge this. Seeing the upcoming merge of #1043 but maybe you can be ahead of the storm with this one.

2021-01-04 13:21 UTC, merged