Clarify error messages
OpenConext/OpenConext-engineblock pull request #1104
Opened 2021-04-06 07:17 UTC by Badlapje

Prior to this change, the error messages were very generic and did not specify name of the SP or IDP.

This change tailors the messages to suit the occasion (SP/IDP) where possible.

2021-04-06 09:30 UTC, arnoutt commented on languages/messages.en.php
> +    'error_authorization_policy_violation_desc'       => 'Please contact the service desk of %idpName% if you require access to %spName%. Be sure to mention you tried to access %spName% and that you
1 line above the word 'helpdesk' is used instead of service desk. Would be better to choose 1 and use that consistently. (Service desk?)

2021-04-06 09:32 UTC, arnoutt commented on languages/messages.en.php
> +    'error_unknown_preselected_idp' => 'Error - %spName% not accessible through your %organisationNoun%',
... not accessible through %idpName%

2021-04-06 09:37 UTC, arnoutt commented on languages/messages.en.php
> +    'error_unknown_preselected_idp_desc' => 'The %organisationNoun% that you want to use to login to %spName% did not activate access to it. This means you are unable to use %spName% through %suiteNa
%idpName% did not activate access to %spName%. This means you are currently unable to use %spName% through %suiteName%. Please contact the service desk of %idpName% to request access. State it is about accessing %spName% through %suiteName% and why you need access.

2021-04-06 09:39 UTC, arnoutt commented on languages/messages.en.php
> +    'error_unknown_service_provider_desc'     => '%spName% you are trying to log in to is unknown to %suiteName%. Possibly your %organisationNoun% has never enabled access to %spName%. If you would l
You are trying to log into %spName%, but this is unknown to %suiteName%. Possibly %idpName% has never enabled access to %spName%. If you would like to use it, please contact the service desk of %idpName%.

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.en.php
> +    'error_generic_desc'                => 'Logging in has failed and we don\'t know exactly why. Please try again first by going back to %spName% and logging in again. If this doesn\'t work, please
service desk

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.en.php
> +%idpName% does not provide the mandatory information. Therefore, you can not use this %spName%. Please contact %idpName% and tell them one or more of the the following required attribute(s) are missi
%idpName% does not provide the mandatory information. Therefore, you can not use %spName%. Please contact the service desk of %idpName% and state one or more of the the following required attribute(s) are missing within %suiteName%:

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.en.php
> +    'error_invalid_attribute_value_desc' => '%idpName% sends a value for attribute %attributeName% ("%attributeValue%") which is not allowed for this %organisationNoun%. Therefore you cannot log in.
service desk

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.en.php
> +    'error_clock_issue_desc' => 'This is likely because the difference in time between %idpName% and %suiteName% it too large. Please verify that the time on the IdP is correct.',
IdP -> %organisationNoun%?

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.nl.php
> +    'error_authorization_policy_violation_desc'       => 'Neem contact op met de servicedesk van %idpName% als je toegang tot %spName% wilt. Vermeld daarbij dat je probeerde in te loggen op %spName%
service desk

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.nl.php
> +    'error_unknown_preselected_idp' => 'Fout - %spName% niet toegankelijk via %organisationNoun%',
niet toegankelijk via %idpName%

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.nl.php
> +    'error_unknown_preselected_idp_desc' => 'De %organisationNoun% waarmee je wilt inloggen heeft toegang tot %spName% niet geactiveerd. Dat betekent dat jij geen gebruik kunt maken van deze dienst v
%idpName% heeft de toegang tot %spName% niet geactiveerd. Dat betekent dat je op dit moment geen gebruik kunt maken van %spName% via %suiteName%. Neem contact op met de helpdesk van %idpName% om toegangaan te vragen. Vermeld daarbij dat je via %suiteName% toegang wilt tot %spName% en leg ook uit waarom.

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.nl.php
> +    'error_unknown_service_provider_desc'     => '%spName% is onbekend bij %suiteName%. Wellicht heeft je %organisationNoun% toegang tot deze dienst niet geactiveerd. Wil je gebruik maken van %spName
%spName% is onbekend bij %suiteName%. Wellicht heeft %idpName% toegang tot %spName% niet geactiveerd. Wil je gebruik maken van %spName%, neem dan contact op met de helpdesk van %idpName% en leg uit dat je toegang wilt tot %spName% via %suiteName%.

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.nl.php
> +        Neem alstublieft contact op met %idpName%. Geef hierbij de onderstaande informatie door.
Neem contact op met de helpdesk van %idpName%. Geef hierbij de onderstaande informatie door.

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.en.php
> +    'error_authorization_policy_violation_desc'       => 'Please contact the service desk of %idpName% if you require access to %spName%. Be sure to mention you tried to access %spName% and that you
I'd propse service desk for EN and helpdesk for NL.

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.nl.php
> +    'error_authn_context_class_ref_blacklisted_desc' => '<p>Je kunt niet inloggen omdat %idpName% een waarde stuurde voor AuthnContextClassRef die niet is toegestaan. Neem contact op met de servicede
helpdesk

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.nl.php
> +    'error_invalid_mfa_authn_context_class_ref_desc' => '<p>%idpName% vereist multi-factor authenticatie voor deze dienst. Je tweede factor kon echter niet gevalideerd worden. Neem contact op met de
helpdesk

2021-04-06 09:54 UTC, arnoutt commented on languages/messages.nl.php
> +    'error_clock_issue_desc' => 'Dit komt waarschijnlijk doordat de tijd tussen %idpName% en %suiteName% te ver uiteen loopt. Controleer de tijd op de IdP.',
IdP -> %organisationNoun%?

2021-04-06 11:07 UTC, MKodde requested changes
Nice work!

1. Did you run the visual regression error page tests? Please update their snapshots. They will most definitely fail as per this change.
2. Maybe ask @domgon for review of the changed Portuguese translations?
3. See some feedback below. 

PS I've left the review of the textual changes up to @arnoutt.

2021-04-06 11:07 UTC, MKodde commented on library/EngineBlock/ApplicationSingleton.php
> +            $feedbackInfo['identityProviderName'] = $this->getidentityProviderName($idpEntityId);
In case the get method returns `''`, maybe not set the IdPName on the feedback info? Preventing harder to read sentences on the error page. Or if that is unacceptable, maybe set an 'idpnotfound' filler text. Let's discus this.

2021-04-06 11:07 UTC, MKodde commented on library/EngineBlock/ApplicationSingleton.php
> +            $identityProvider = $this->getDiContainer()->getMetadataRepository()->fetchIdentityProviderByEntityId($identityProviderId);
The annotation can be rid of the (incorrect) $idp varname. Either correct it or remove it altogether. The fetch method should have a return type so adding the additional type hint might be overkill

2021-04-06 11:07 UTC, MKodde commented on src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/FeedbackController.php
> +        if ($feedbackInfo['IdentityProvider'] || $feedbackInfo['IdP'] || $feedbackInfo['identityProvider']) {
Are these three variations really used on the error pages?

2021-04-06 11:30 UTC, Badlapje commented on library/EngineBlock/ApplicationSingleton.php
> +            $identityProvider = $this->getDiContainer()->getMetadataRepository()->fetchIdentityProviderByEntityId($identityProviderId);
fixed it

2021-04-06 11:33 UTC, Badlapje commented on library/EngineBlock/ApplicationSingleton.php
> +            $feedbackInfo['identityProviderName'] = $this->getidentityProviderName($idpEntityId);
Good point, but is that possible?  If it is, should we not take the same precaution on line 255 with the serviceProviderName?

2021-04-06 11:35 UTC, Badlapje commented on languages/messages.en.php
> +    'error_authorization_policy_violation_desc'       => 'Please contact the service desk of %idpName% if you require access to %spName%. Be sure to mention you tried to access %spName% and that you
Overal aangepast.

2021-04-06 11:36 UTC, Badlapje commented on languages/messages.en.php
> +    'error_generic_desc'                => 'Logging in has failed and we don\'t know exactly why. Please try again first by going back to %spName% and logging in again. If this doesn\'t work, please
aangepast overal

2021-04-06 11:38 UTC, Badlapje commented on languages/messages.en.php
> +    'error_invalid_attribute_value_desc' => '%idpName% sends a value for attribute %attributeName% ("%attributeValue%") which is not allowed for this %organisationNoun%. Therefore you cannot log in.
adjusted

2021-04-06 11:39 UTC, Badlapje commented on languages/messages.nl.php
> +    'error_authorization_policy_violation_desc'       => 'Neem contact op met de servicedesk van %idpName% als je toegang tot %spName% wilt. Vermeld daarbij dat je probeerde in te loggen op %spName%
adjusted

2021-04-06 11:39 UTC, Badlapje commented on languages/messages.nl.php
> +        Neem alstublieft contact op met %idpName%. Geef hierbij de onderstaande informatie door.
adjusted

2021-04-06 11:41 UTC, Badlapje commented on languages/messages.nl.php
> +    'error_authn_context_class_ref_blacklisted_desc' => '<p>Je kunt niet inloggen omdat %idpName% een waarde stuurde voor AuthnContextClassRef die niet is toegestaan. Neem contact op met de servicede
adjusted

2021-04-06 11:42 UTC, Badlapje commented on languages/messages.nl.php
> +    'error_invalid_mfa_authn_context_class_ref_desc' => '<p>%idpName% vereist multi-factor authenticatie voor deze dienst. Je tweede factor kon echter niet gevalideerd worden. Neem contact op met de
adjusted

2021-04-06 12:28 UTC, Badlapje commented on languages/messages.nl.php
> +    'error_clock_issue_desc' => 'Dit komt waarschijnlijk doordat de tijd tussen %idpName% en %suiteName% te ver uiteen loopt. Controleer de tijd op de IdP.',
adjusted

2021-04-06 12:29 UTC, Badlapje commented on languages/messages.en.php
> +    'error_clock_issue_desc' => 'This is likely because the difference in time between %idpName% and %suiteName% it too large. Please verify that the time on the IdP is correct.',
adjusted

2021-04-06 13:52 UTC, Badlapje commented on languages/messages.en.php
> +%idpName% does not provide the mandatory information. Therefore, you can not use this %spName%. Please contact %idpName% and tell them one or more of the the following required attribute(s) are missi
adjusted

2021-04-06 13:58 UTC, Badlapje commented on src/OpenConext/EngineBlockFunctionalTestingBundle/Features/ClearErrorMessages.feature
> +     Then I should see "Error - OpenConext Identities Inc unknown"
true, does this happen?  I thought if we have an entityId of an IDP we always know the IDP?

2021-04-07 06:54 UTC, MKodde reviewed
Hi, I'm back with a more in depth review of the different feedback pages. I found three possible issues. Where the SP or IdP name might not be available. Maybe create a fallback for when the name is not there?

2021-04-07 06:54 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Feedback/unknown-identity-provider.html.twig
> +{% block errorMessage %}{{ 'error_unknown_identity_provider_desc'|trans({'%idpName%': feedbackInfoMap['identityProviderName']})|raw }}{% endblock %}
I don't think the IdP name will  be available here.

2021-04-07 06:54 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Feedback/unknown-error.html.twig
> +{% block errorMessage %}{{ 'error_generic_desc'|trans({'%spName%': feedbackInfoMap['serviceProviderName'], '%idpName%': feedbackInfoMap['identityProviderName']})|raw }}{% endblock %}
Given this is a catch-all error page, the chance we have an IdP/SP name here is not guaranteed. Maybe create three different feedback options here? One with a know SP, one with a  known IdP, and finally a complete SP and IdP pair version?

2021-04-07 06:54 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Feedback/unknown-service-provider.html.twig
> +{% block errorMessage %}{{ 'error_unknown_service_provider_desc'|trans({'%spName%': feedbackInfoMap['serviceProviderName']})|raw }}{% endblock %}
If the SP is unknown, chances are we do not have a name for it either.

2021-04-07 11:46 UTC, Badlapje commented on src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/FeedbackController.php
> +        if ($feedbackInfo['IdentityProvider'] || $feedbackInfo['IdP'] || $feedbackInfo['identityProvider']) {
They are indeed on the test pages.  I can take the opportunity to streamline them instead of doing it hackish here.  Seems like a good idea, but i don't know whether that'd break something somewhere.  Guess i'll notice ;-)

2021-04-07 12:59 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Feedback/unknown-service-provider.html.twig
> +{% block errorMessage %}{{ 'error_unknown_service_provider_desc'|trans({'%spName%': feedbackInfoMap['serviceProviderName']})|raw }}{% endblock %}
that's what i thought, but then it is there in the debug examples.  Weirdness!

2021-04-07 13:24 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Feedback/unknown-service-provider.html.twig
> +{% block errorMessage %}{{ 'error_unknown_service_provider_desc'|trans({'%spName%': feedbackInfoMap['serviceProviderName']})|raw }}{% endblock %}
fixed

2021-04-07 13:33 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Feedback/unknown-error.html.twig
> +{% block errorMessage %}{{ 'error_generic_desc'|trans({'%spName%': feedbackInfoMap['serviceProviderName'], '%idpName%': feedbackInfoMap['identityProviderName']})|raw }}{% endblock %}
fixed

2021-04-07 13:55 UTC, Badlapje commented on src/OpenConext/EngineBlockFunctionalTestingBundle/Controllers/FeedbackController.php
> +        if ($feedbackInfo['IdentityProvider'] || $feedbackInfo['IdP'] || $feedbackInfo['identityProvider']) {
streamlined

2021-04-07 13:55 UTC, Badlapje commented on library/EngineBlock/ApplicationSingleton.php
> +            $feedbackInfo['identityProviderName'] = $this->getidentityProviderName($idpEntityId);
fixed in the three marked templates below

2021-04-07 19:17 UTC, Badlapje commented on languages/messages.en.php
> +    'error_unknown_preselected_idp' => 'Error - %spName% not accessible through your %organisationNoun%',
fixed

2021-04-07 19:18 UTC, Badlapje commented on languages/messages.en.php
> +    'error_unknown_preselected_idp_desc' => 'The %organisationNoun% that you want to use to login to %spName% did not activate access to it. This means you are unable to use %spName% through %suiteNa
fixed

2021-04-07 19:34 UTC, Badlapje commented on languages/messages.en.php
> +    'error_unknown_service_provider_desc'     => '%spName% you are trying to log in to is unknown to %suiteName%. Possibly your %organisationNoun% has never enabled access to %spName%. If you would l
fixed

2021-04-08 08:45 UTC, Badlapje commented
@domgon can you check if the portugese translations are ok?

2021-04-28 14:07 UTC, Badlapje commented
Closed as this was split between #1112  and #1130

2021-04-28 14:07 UTC, closed without merging