Allow AuthnRequest based stepup requests
OpenConext/OpenConext-engineblock pull request #1105
Opened 2021-04-06 11:54 UTC by MKodde

When the AuthnContextClassRefs contain valid LoA(s), then they are to be included in the step up decision process.

This PR is still WIP, but should not be far off.

2021-04-14 18:46 UTC, thijskh commented on src/OpenConext/EngineBlock/Stepup/StepupDecision.php
>          return ($this->spLoa || $this->idpLoa || count($this->authnRequestLoas) > 0 || count($this->pdpLoas) > 0);
If we've already done getStepupLoa(), can we then make test in the `return` statement much simpler?

2021-04-15 08:28 UTC, Badlapje requested changes
I haven't tested it functionally as i was unsure how to do so.  That said: nice work!

One small remark, other than that it's good to go i think.

2021-04-15 08:28 UTC, Badlapje commented on src/OpenConext/EngineBlock/Stepup/StepupDecision.php
> +        return ($this->spLoa || $this->idpLoa || count($this->authnRequestLoas) > 0 || count($this->pdpLoas) > 0);
this return statement seems to be identical to the if statement in `$this->allowNoToken`.  Can both not be abstracted into a method that can be called?

2021-04-15 08:28 UTC, Badlapje commented on src/OpenConext/EngineBlock/Stepup/StepupDecision.php
> +        return ($this->spLoa || $this->idpLoa || count($this->authnRequestLoas) > 0 || count($this->pdpLoas) > 0);
would also have the advantage of making the method name descriptive so it's easier to follow what's going on.

2021-04-15 09:49 UTC, thijskh commented on src/OpenConext/EngineBlock/Stepup/StepupDecision.php
>          return ($this->spLoa || $this->idpLoa || count($this->authnRequestLoas) > 0 || count($this->pdpLoas) > 0);
Or remove it.

2021-04-15 12:13 UTC, MKodde commented on src/OpenConext/EngineBlock/Stepup/StepupDecision.php
> +        return ($this->spLoa || $this->idpLoa || count($this->authnRequestLoas) > 0 || count($this->pdpLoas) > 0);
Good call!

2021-04-15 12:22 UTC, MKodde commented on src/OpenConext/EngineBlock/Stepup/StepupDecision.php
>          return ($this->spLoa || $this->idpLoa || count($this->authnRequestLoas) > 0 || count($this->pdpLoas) > 0);
Yes, I think you are right. A `null` from the `getStepupLoa` method equals the return statements logical comparison. We can simply return `true` at that point.

2021-04-15 13:50 UTC, Badlapje approved these changes
Nice work! :shipit:

2021-04-15 13:54 UTC, merged