Include Twig linting in CI pipeline
OpenConext/OpenConext-engineblock pull request #1108
Opened 2021-04-08 09:24 UTC by MKodde

2021-04-08 09:47 UTC, Badlapje requested changes

2021-04-08 09:47 UTC, Badlapje commented on .github/workflows/test-integration.yml
> +                      php72 app/console lint:twig theme/
Maybe also add this in the package.json and/or the documentation?

2021-04-14 06:12 UTC, MKodde commented on .github/workflows/test-integration.yml
> +                      php72 app/console lint:twig theme/
Wilco, sir!

2021-04-14 06:42 UTC, MKodde commented on build.xml
> +    </target>
@Badlapje ended up adding this to the build.xml instead of the too much unrelated packages.json npm scripts. Are you with me on this one? Or can you argue otherwise?

2021-04-14 07:11 UTC, Badlapje commented on build.xml
> +    </target>
I like adding it here, but I'm not sure a front-ender who's theming will think to look here or know / understand how to get it working.  So that'd require including it in the theming documentation with some instructions on how to run it.  The advantage a package.json has is that it's self-documenting & known territory for frontenders.

2021-04-15 13:51 UTC, Badlapje approved these changes
❤️ this PR!

2021-04-15 13:54 UTC, merged