Replace the hamburger and search icon
OpenConext/OpenConext-engineblock pull request #1116
Opened 2021-04-19 12:48 UTC by Badlapje

Prior to this change, these were a seperate image meaning increased load
times.

This change replaces the icons with a font-awesome icon.

Issue on pivotal: https://www.pivotaltracker.com/n/projects/1425900

2021-04-19 14:08 UTC, MKodde requested changes
Nice work, I haven't test-driven this yet. But already have some suggestions:

1. You can remove the hamburger and search svg's now am I right?
2. Do we need to verify the EN/NL/PT translations? Consider adding a google trans translation for the PT text.
3. Do the visual regression snapshots need updating?

Going to test this in browser now.

After some functional testing:
1. Do you plan to replace the spinner icon? Or would that be too great a regression?
2. I don't think the user.svg icon is used anywhere. Maybe remove it too?

2021-04-19 17:05 UTC, Badlapje commented
>     1. You can remove the hamburger and search svg's now am I right?

good one, done!
 
>     2. Do we need to verify the EN/NL/PT translations? Consider adding a google trans translation for the PT text.

I just asked arnout about them.  Added a portugese translation.

>     3. Do the visual regression snapshots need updating?

Good one!  Totally forgot about those.  😊 

>     1. Do you plan to replace the spinner icon? Or would that be too great a regression?

I recommended the fa-spinner to arnout , but as he correctly pointed out: the spinner was already replaced in the redesign.  So we left it in place.
 
>     2. I don't think the user.svg icon is used anywhere. Maybe remove it too?

Done.

2021-04-19 18:33 UTC, MKodde reviewed
Is it me, or did the screenshots not end up in your commit stage? Other then that! Things are looking up! I found a possible translation thingy.

2021-04-19 18:33 UTC, MKodde commented on theme/openconext/templates/modules/Authentication/View/Proxy/wayf.html.twig
> +        <button class="search"><span class="sr-only">Search</span><i class="fa fa-search" aria-hidden="true"></i></button>
Totally missed this one in my first review round. Shouldn't the 'Search' text be a translation?

2021-04-19 18:33 UTC, MKodde commented on theme/openconext/translations/messages.pt.php
> +    'hamburger_screenreader'     => 'pular para o rodapé',
Toalha de banho bem feita!

2021-04-20 13:46 UTC, Badlapje commented
@MKodde for the screenshots: we don't screenshot the pages where these changes reside.  So nothing needs replacing there.  Added it to my todo to make that second visual test PR.

2021-04-20 13:47 UTC, Badlapje commented on theme/openconext/translations/messages.pt.php
> +    'hamburger_screenreader'     => 'pular para o rodapé',
😆

2021-04-20 13:51 UTC, Badlapje commented on theme/openconext/templates/modules/Authentication/View/Proxy/wayf.html.twig
> +        <button class="search"><span class="sr-only">Search</span><i class="fa fa-search" aria-hidden="true"></i></button>
well spotted!

2021-04-22 13:37 UTC, MKodde approved these changes
Grand!

2021-04-22 13:55 UTC, merged