WIP: Add a global site notice
OpenConext/OpenConext-engineblock pull request #1128
Opened 2021-04-20 17:01 UTC by Badlapje

Prior to this release there was no way to set a global site notice.

This release will add the ability to set a site notice via the parameters.yml file.  

More info can be found at the pivotal story: https://www.pivotaltracker.com/story/show/176815369

2021-04-22 14:20 UTC, MKodde requested changes
You did a great job. I have some suggestions that hopefully makes this PR a little less involved.

2021-04-22 14:20 UTC, MKodde commented on languages/messages.en.php
> +    'warning_allowed_html'  =>  '<a><u><i><br><wbr><strong><em><blink><marquee><p><ul><ol><dl><li><dd><dt><div><span><blockquote><hr><h2><h3><h4><h5><h6>',
The parameters.yml might be a more suitable place to configure this wouldn't you say? I can't think why English readers should have a limited set of elements compared to the Dutch or Portuguese. Even consider hardcoding this and not making it configurable.

2021-04-22 14:20 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/site-notice.html.twig
> +{% if showGlobalSiteNotice %}
At this point you could use the Twig thingy to inform the template if the notice should be shown or not

2021-04-22 14:20 UTC, MKodde commented on theme/README.md
> +- globalSiteNotice: if you want to add a siteNotice you can add the text for it here.  You can test this by going to `/functional-testing/wayf?showGlobalSiteNotice=1&globalSiteNotice=<text>` or `/fun
My man! Thanks for updating this right away

2021-04-22 14:20 UTC, MKodde commented on theme/openconext/templates/modules/Authentication/View/Proxy/consent.html.twig
> +{#            {% if showConsentExplanation and consentSettings.consentExplanationIn(app.request.locale, spEntityId) %}#}
You removed this later I presume, If not please resolve this

2021-04-22 14:20 UTC, MKodde commented on theme/README.md
> +- cookie removal page: `templates > modules > authentication > view > identityprovider > remove-cookies.html.twig`.  You can use `https://engine.vm.openconext.org/authentication/idp/remove-cookies` t
Thanks for amending this to the readme!

2021-04-22 14:20 UTC, MKodde commented on src/OpenConext/EngineBlockBundle/Controller/IndexController.php
> +        $settings = EngineBlock_ApplicationSingleton::getInstance()->getDiContainer();
We don't want to litter our 'modern' Symfony application with stuff from the legacy 'library'. You can use the adapter solution for this. I think there are a couple of examples of this in the application. If you'd like we can have a look around together.

2021-04-26 14:19 UTC, Badlapje commented on app/config/parameters.yml.dist
> +    global.site_notice.content: '<p>There is nothing wrong with your television set. <strong>Do not attempt to adjust the picture.</strong> We are controlling transmission. If we wish to make it loud
@thijskh do you agree with the default site_notice content being a translatable string?  Makes sense to me, but that does mean there's two places where it needs to be configured for anyone wanting to show it?

2021-04-26 14:20 UTC, Badlapje commented on languages/messages.en.php
> +    'warning_allowed_html'  =>  '<a><u><i><br><wbr><strong><em><blink><marquee><p><ul><ol><dl><li><dd><dt><div><span><blockquote><hr><h2><h3><h4><h5><h6>',
Good one, adjusting!

2021-04-26 14:40 UTC, Badlapje commented on library/EngineBlock/Corto/Module/Service/ProvideConsent.php
> +                'globalSiteNotice' => $globalSiteNotice,
I created a twig helper modelled on the feedback.php helper.  That means the check can be contained in the site-notice.html.twig, which is perfect (all logic in one place).

2021-04-26 14:43 UTC, Badlapje commented on src/OpenConext/EngineBlockBundle/Controller/IndexController.php
> +        $settings = EngineBlock_ApplicationSingleton::getInstance()->getDiContainer();
the twig helper actually resolved this too :-)

2021-04-26 16:17 UTC, Badlapje commented on theme/openconext/templates/modules/Authentication/View/Proxy/consent.html.twig
> +{#            {% if showConsentExplanation and consentSettings.consentExplanationIn(app.request.locale, spEntityId) %}#}
resolved

2021-04-26 16:18 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/Shared/site-notice.html.twig
> +{% if showGlobalSiteNotice %}
i ❤️ the twig extension ... so much cleaner that way 💯

2021-04-27 13:14 UTC, Badlapje commented on app/config/parameters.yml.dist
> +    global.site_notice.content: '<p>There is nothing wrong with your television set. <strong>Do not attempt to adjust the picture.</strong> We are controlling transmission. If we wish to make it loud
> Given this is a feature toggle, may I suggest moving this config to around line 200 and renaming it in to something along the lines: `feature_show_global_site_notice: false`

I actually considered this.  However, it seems that those feature toggles are mainly concerning technical stuff (encrypting assertions, using the metadata api, ... ).  This toggle is more akin to the feature toggles we have that are higher up in parameters.yml such as "wayf.display_default_idp_banner_on_wayf" or "wayf.remember_choice", where we display parts of the frontend based on a toggle.  Given that fit, I've included it there.  Is that a reasoning you can follow @MKodde ?

2021-04-28 07:29 UTC, Badlapje commented on app/config/parameters.yml.dist
> +    global.site_notice.content: '<p>There is nothing wrong with your television set. <strong>Do not attempt to adjust the picture.</strong> We are controlling transmission. If we wish to make it loud
fixed translations

2021-04-28 08:42 UTC, MKodde commented on app/config/parameters.yml.dist
> +    global.site_notice.content: '<p>There is nothing wrong with your television set. <strong>Do not attempt to adjust the picture.</strong> We are controlling transmission. If we wish to make it loud
Thanks for your motivation, I can certainly live with that!

2021-04-28 09:19 UTC, MKodde reviewed
You are getting even closer now. Some things stood out to me:

1. The skeune warning notices did not look very skeune yet ;) See screenshots below.
2. The Engine homepage did not seem to show the site notice, nor did the auth debug landing page and the error/feedback page. Maybe that is intentional?
3. See some optimization suggestions for the awesome global site notice Twig Extension.

![Screenshot_2021-04-28 OpenConext - Select an account to login to DisplayName](https://user-images.githubusercontent.com/28252948/116379304-2c89b780-a813-11eb-8389-37610d8b2c36.png)
![Screenshot_2021-04-28 OpenConext - Review your information that will be shared ](https://user-images.githubusercontent.com/28252948/116379309-2d224e00-a813-11eb-903a-73fb562d1881.png)

2021-04-28 09:19 UTC, MKodde commented on src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/GlobalSiteNotice.php
> +        $this->diContainer = $application->getDiContainer();
I see down below you use the diContainer to load the `shouldDisplayGlobalSiteNotice` and `getAllowedHtmlForNotice` data from the container. This however is discouraged, you can directly pass those parameters to this service in the service definition. That way we are not dependent on the library (old EB) code.

2021-04-28 09:19 UTC, MKodde commented on src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/GlobalSiteNotice.php
> +    }
I do not like this setup much. Business code should not be test aware in my opinion. Alternatively you could create a test stand in for the GlobalSiteNotice extension.

2021-04-28 09:19 UTC, MKodde commented on src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/GlobalSiteNotice.php
> +        if ($this->isTest()) {
When the `isTest` portion is moved to a test stand-in you can also move the dummy text to that class, making this much cleaner.

2021-04-28 09:19 UTC, MKodde commented on src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/GlobalSiteNotice.php
> +            return (bool) $this->request->get('showGlobalSiteNotice', false);
Getting rid of the 'isTest' feature of this service will also result in the loss of the requestStack dependency.

2021-04-28 09:29 UTC, MKodde commented on src/OpenConext/EngineBlockBundle/Resources/config/services.yml
> +            - "@translator"
Instead of injecting the application service, you can inject the parameters you are loading from the application singletons di-container later-on here directly. 

Parameters can be accessed suchlike "%locale%"

2021-04-28 11:46 UTC, Badlapje commented on src/OpenConext/EngineBlockBundle/Twig/Extensions/Extension/GlobalSiteNotice.php
> +        $this->diContainer = $application->getDiContainer();
hah, learn something new every day 👍   Even better this way ^__^

2021-04-28 12:45 UTC, Badlapje reviewed
>     1. The skeune warning notices did not look very skeune yet ;) See screenshots below.

Is it possible you had old CSS?  It looks like this for me:
![image](https://user-images.githubusercontent.com/4058016/116404636-1f7ac180-a82f-11eb-8977-b4d376802474.png)
![image](https://user-images.githubusercontent.com/4058016/116405395-e2fb9580-a82f-11eb-9955-9f3c75d7ebf8.png)

>     2. The Engine homepage did not seem to show the site notice, nor did the auth debug landing page and the error/feedback page. Maybe that is intentional?

For the error/feedback page: intentional.  As for the auth debug page: I assumed it's something akin to the error page.  Not a good page to show the site-notice.  Not sure in what context it's shown to normal users, but i figured it's the same type as an error page so didn't show it there.

For the homepage: should be visible (but in material style as that's not been redesigned yet):
![image](https://user-images.githubusercontent.com/4058016/116405606-20602300-a830-11eb-96f0-b941dcc2fdde.png)

>     3. See some optimization suggestions for the awesome global site notice Twig Extension.

❤️ thx for the help!

Not sure why github made this comment a review, but here it is.

2021-04-29 06:29 UTC, MKodde approved these changes
I'm happy with the change now! My screenshots musthavebeen old css in  browsercache. 

The debug authentication page is a test feature built into the EngineBlock. Here you can send a dummy AuthnRequest through EngineBlock. The response of the IdP will be shown on the debug page. Here you can see which attributes where released among other things. Given the debug nature of this page, it's probably OK not to show the site notice there. On the other hand, why not? I'd say, ask the PM's what they want in this regard. While at it maybe ask them if the dummy texts are acceptable. I like them, but a more conservative lorem ipsum text might be more fitting? Again something for the PO's to decide upon.

2021-04-29 07:30 UTC, merged