Support removal of consent by collab person id and SP enitty id
OpenConext/OpenConext-engineblock pull request #1160
Opened 2021-09-20 11:36 UTC by MKodde

An API endpoint is created to remove a single consent row based on a user id and a SP entity id. This allows the profile end user to retract consent for services they have previously granted consent to.

https://www.pivotaltracker.com/story/show/179490276

2021-09-21 09:53 UTC, thijskh commented on src/OpenConext/EngineBlockBundle/Authentication/Repository/DbalConsentRepository.php
> +        }
I think we want to log that we did it.

2021-09-21 09:53 UTC, thijskh commented on tests/functional/OpenConext/EngineBlockBundle/Controller/Api/DeprovisionControllerTest.php
> +        $client->request('GET', 'https://engine-api.vm.openconext.org/remove-consent/urn:collab:person:test/https://my-first-sp.test');
I'm not so sure about putting an URL in a URL. I can foresee all kinds of issues if we do not encode this. I am also not so sure that "GET" is the correct method? So maybe we solve both in one go and change it to a POST where we can supply the variables in the body?

2021-09-21 10:17 UTC, MKodde commented on src/OpenConext/EngineBlockBundle/Authentication/Repository/DbalConsentRepository.php
> +        }
I agree, additional logging for the 'happy flow' is meaningful here. May I suggest to perform this logging action in the controller action?

2021-09-21 10:21 UTC, MKodde commented on tests/functional/OpenConext/EngineBlockBundle/Controller/Api/DeprovisionControllerTest.php
> +        $client->request('GET', 'https://engine-api.vm.openconext.org/remove-consent/urn:collab:person:test/https://my-first-sp.test');
Yes! I think using the DELETE verb or maybe POST is better than using a GET request. Delete would be most expressive from a restful point of view. But this would not eliminate the use of query parameters.

2021-12-08 19:14 UTC, thijskh requested changes
The delete is too final. See https://www.pivotaltracker.com/story/show/180576312 for how we envision how soft-delete should work.

2022-05-02 07:40 UTC, thijskh approved these changes

2022-05-02 07:40 UTC, thijskh commented on library/EngineBlock/User.php
> +                    AND ISNULL(deleted_at)';
Not sure this is standard SQL? Should that be `deleted_at IS NULL` instead?

2022-05-02 07:40 UTC, thijskh commented on src/OpenConext/EngineBlock/Service/ConsentService.php
> +                sprintf('An exception occurred while removing consent for a service provider("%s")', $e->getMessage()),
While we're at it, add `$id` and `$serviceProviderEntityId` to the message?

2022-05-02 07:40 UTC, thijskh commented on src/OpenConext/EngineBlockBundle/Authentication/Repository/DbalConsentRepository.php
> +                ISNULL(deleted_at)
as above

2022-05-02 07:40 UTC, thijskh commented on src/OpenConext/EngineBlockBundle/Authentication/Repository/DbalConsentRepository.php
> +            AND ISNULL(deleted_at)
as above

2022-05-02 07:40 UTC, thijskh commented on src/OpenConext/EngineBlockBundle/Authentication/Repository/DbalConsentRepository.php
> +            $this->logger->info(sprintf('Removed consent for hashed user id %s (%s)', sha1($userId), $userId));
I tend to make this a `notice` for now. Can always downgrade if that's too chatty

2022-05-02 07:40 UTC, thijskh commented on src/OpenConext/EngineBlockBundle/Controller/Api/ConsentController.php
> +        if (!$this->featureConfiguration->isEnabled('api.consent_remove')) {
Likely it makes sense to disable all consent endpoints if consent is disabled entirely. But I'll make a separate story for that

2022-05-02 09:06 UTC, MKodde commented on library/EngineBlock/User.php
> +                    AND ISNULL(deleted_at)';
Good point, I changed it to use the IS NULL syntax. Using the method was safe too, but not semantically correct.

2022-05-02 09:38 UTC, merged