Include organization names in Consent DTO
OpenConext/OpenConext-engineblock pull request #1186
Opened 2022-04-14 13:57 UTC by MKodde

Retrieval of the right organization name is implemented to the following
algorithm:

```
    L = current language, "en" is English the global default language.
    If OrganizationDisplayName:L is set, return OrganizationDisplayName:L
    else if OrganizationName:L is set, returnOrganizationName:L
    else if OrganizationDisplayName:"en" is set, return OrganizationDisplayName:"en"
    else if OrganizationName:"en" is set, returnOrganizationName:"en"
    else return "unknown" (should not happen on production, Manage check will be added that always one of the fields is present)
```

This is to support Profile in showing the organization offering the
service on the 'my-services' page

More info and background: https://www.pivotaltracker.com/story/show/176872837

2022-04-14 14:48 UTC, MKodde commented on src/OpenConext/EngineBlock/Authentication/Dto/Consent.php
> +            // Fallback to english display name
Yup, that makes perfect sense!

2022-04-14 15:05 UTC, thijskh reviewed
Maybe add return type, codewise ok, testsuite needs fixing

2022-04-14 15:05 UTC, thijskh commented on src/OpenConext/EngineBlock/Authentication/Dto/Consent.php
> +    private function getOrganizationDisplayNameFields()
`: array`?

2022-04-19 06:19 UTC, MKodde commented on src/OpenConext/EngineBlock/Authentication/Dto/Consent.php
> +    private function getOrganizationDisplayNameFields()
Another good suggestion! I typehinted the rest of the methods too, and cleaned up irrelevant docblock

/BSR :deciduous_tree:

2022-04-19 06:31 UTC, VadimSchmitz approved these changes

2022-04-19 08:44 UTC, thijskh approved these changes

2022-04-19 08:45 UTC, thijskh requested changes
Tests still fail though

2022-04-19 09:58 UTC, thijskh approved these changes

2022-04-21 09:28 UTC, merged