Remove legacy cache headders on certificate output
OpenConext/OpenConext-engineblock pull request #1220
Opened 2023-02-20 12:46 UTC by thijskh

We do not add these headers on other metadata which contains the certificate. Also the IE specific handling is obsolete. PEMs are not binary. Simplify by just stopping to add all the explicit things only for the certificate.

2023-03-02 10:14 UTC, MKodde requested changes
Nice work. See some suggestions below. Chief amongst which the suggestion regarding serving of files.

2023-03-02 10:14 UTC, MKodde commented on src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
>          $this->router = $router;
Both the router and the ebApplicationSingleton seem unused in this controller. Consider removing them under the boyscout rule.

2023-03-02 10:14 UTC, MKodde commented on src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
> +        $response->headers->set('Content-Type', 'application/x-pem-file');
This will probably work as the browser itself will probably pick this up as a file download. But to ensure good compatibility for any browser. And to adhere to the best practices consider setting a disposition: attachment or use the binary file response type:

`https://symfony.com/doc/3.4/components/http_foundation.html#serving-files`

2023-03-03 12:17 UTC, thijskh commented on src/OpenConext/EngineBlockBundle/Controller/MetadataController.php
> +        $response->headers->set('Content-Type', 'application/x-pem-file');
Note that we already serve the XML files in this way in this same file. I wanted to keep it consistent so do it the same for XML and PEM since I personally do not perceive a difference here. In the interest of simplicity I opted to make the PEM serving the same as the XML serving.

2023-03-03 13:00 UTC, thijskh commented on src/OpenConext/EngineBlock/Xml/MetadataProvider.php
> +        return $this->keyPairFactory->buildFromIdentifier($keyId)->getCertificate()->toPem();
I don't think this can happen because buildFromIdentifier will build an X509KeyPair with both private and public key set so there's not practical way we can arrive at that situation. All the better throw an error if this occurs because it should never.

2023-03-07 06:35 UTC, MKodde commented on src/OpenConext/EngineBlock/Xml/MetadataProvider.php
> +        return $this->keyPairFactory->buildFromIdentifier($keyId)->getCertificate()->toPem();
Thanks for checking that out

2023-03-07 06:38 UTC, MKodde approved these changes

2023-03-07 15:54 UTC, merged