Send NoPassive status response back to issuing SP
OpenConext/OpenConext-engineblock pull request #885
Opened 2020-08-24 11:48 UTC by MKodde

These NoPassive status responses are sent by the IdP who is not
able/allowed to process a Passive authentication.

Previously we would show a custom error page. But on this occasion it's
better to let the SP decide how to proceed in this situation.

See: https://www.pivotaltracker.com/story/show/164238276

2020-08-24 15:22 UTC, pablothedude requested changes
Maybe the response should happen later on in the process, could you verify this?

2020-08-24 15:22 UTC, pablothedude commented on library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
> +        // Test if we should return a no passive status response back to the SP
Doesn't this have to take place after the response signature method, requester chain validation and the key check?

2020-08-25 06:57 UTC, MKodde commented on library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
> +        // Test if we should return a no passive status response back to the SP
I'm not sure that would be wise if at all possible. My rationale is to exit as soon as possible. But maybe @thijskh, @phavekes  or @pmeulen can answer your question?

2020-08-25 07:08 UTC, pablothedude commented on library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
> +        // Test if we should return a no passive status response back to the SP
@MKodde it seems possible according to our tests if I move the logic down (after those checks).

2020-08-25 07:14 UTC, MKodde commented on library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
> +        // Test if we should return a no passive status response back to the SP
Yes, it might work. But given the situation in the Bindings.php::receiveResponse method where I return the ResponseAnnotationDecorator from the catch block. I can't be sure what other problems are present in that response. It might have failed on any precondition. Processing the SAML Response after preconditions failed, in the AssertionConsumer might result in unexpected behaviour that might not be simulated in the Behat tests.

2020-08-25 07:15 UTC, thijskh commented on library/EngineBlock/Corto/Module/Service/AssertionConsumer.php
> +        // Test if we should return a no passive status response back to the SP
I prefer that we take action only after having performed the checks "is this even a legitimate message". Doing it early might enable a (yet unkown) security issue and we might miss useful things like 'additional logging' that are futher below in the code, on this type of response.

2020-08-25 09:59 UTC, pablothedude approved these changes
:+1: thanks!

2020-08-25 11:16 UTC, merged