Remove the remaining eduGAIN metadafields
OpenConext/OpenConext-engineblock pull request #922
Opened 2020-10-05 10:04 UTC by MKodde

This PR consists of a migration that drops the last database table related eduGAIN references.

The commit warns: `To be released post EngineBlock 6.2 for rollbackability` Now that we are in the 6.3 tier, this can be merged now.

2020-10-05 12:01 UTC, thijskh approved these changes

2020-10-05 12:20 UTC, thijskh requested changes
On production we have publish_in_edugain but not publish_in_edu_gain_date. So deploying this would break on the migration I think

2020-10-05 12:22 UTC, tvdijen commented
I have both on all my instances..

2020-10-05 14:44 UTC, MKodde commented
I was not aware of an awesome Doctrine Migration feature where you can check if a certain column or index exists before altering it.

I used that on both Migrations that where causing issues on the 6.3.x migration path.

2020-10-05 14:50 UTC, tvdijen commented
This should probably be used for adding / removing colums as well, instead of fiddling around with SQL queries..
The only downside I've seen so far is that it doesn't support a specific location for the new column..

2020-10-05 16:17 UTC, thijskh approved these changes

2020-10-06 06:15 UTC, MKodde commented
@tvdijen that's certainly worth looking into for the future. I usually record a migration using the diff tool. But (re)writing them using the provided methods might help creating more robust migrations.

For now I'm merging these changes.

2020-10-06 06:15 UTC, merged