Hide disconnected idps when the flag is true
OpenConext/OpenConext-engineblock pull request #937
Opened 2020-10-15 06:44 UTC by Badlapje

Hide unconnected idps when the flag says they are not desired

2020-10-15 14:39 UTC, MKodde requested changes
Fine work! See some feedback below.

2020-10-15 14:39 UTC, MKodde commented on theme/README.md
> +- showConsentExplanation: whether or not to show a special explanation on the consent page.  There is currently no testpoint for this.
Nice addition. But I think you misinterpreted my idea to add a description of these parameters to a readme file. I was talking about the `parameters.yml` EngineBlock feature flags.

These parameters described above are already in this readme: https://github.com/OpenConext/OpenConext-engineblock/blob/master/docs/js_testing.md

let's leave this as-is for now as this section demonstrates the available parameters in a more user friendly manner. Let's merge things in the 'leftover' ticket at the end of this development effort. Same goes for documenting the parameters.yml feature flags

2020-10-15 14:39 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
> +        {% endif %}
Please rewrite this into a single blocked control statement. A single if without the else block should be possible here.

2020-10-15 14:39 UTC, MKodde commented on theme/cypress/integration/skeune/wayf/WayfGeneralBehaviour.js
> +    });
:muscle:

2020-10-15 16:04 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/WAYF/idp/idpList.html.twig
> +        {% endif %}
fixed

2020-10-19 07:07 UTC, MKodde approved these changes

2020-10-19 07:21 UTC, merged