Increae whitespace between consent title and text
OpenConext/OpenConext-engineblock pull request #963
Opened 2020-11-04 09:32 UTC by MKodde

The whitespace needed to be a bit more roomy. By setting a margin-right on the title, this should not interfere with other viewports as they render title and text beneath each other.

2020-11-04 14:07 UTC, Badlapje requested changes
Small change to prevent any possible issues.  Other than that looking good!

2020-11-04 14:07 UTC, Badlapje commented on theme/base/stylesheets/pages/consent.scss
> +                    margin-right: 0.5rem;
I'd reset the margin-right to 0 for mobile (line 179) to be sure it doesn't add some weird layout breakage for some IDP attributes.  It's unlikely, but experience learns that it's better to prevent it alltogether.

2020-11-04 15:02 UTC, MKodde commented on theme/base/stylesheets/pages/consent.scss
> +                    margin-right: 0.5rem;
Good suggestion, it did look good on smaller screens, but better safe then sorry!

2020-11-10 11:12 UTC, Badlapje approved these changes
:shipit:

2020-11-10 13:37 UTC, merged