Set other consent icons at privacy and sec section
OpenConext/OpenConext-engineblock pull request #964
Opened 2020-11-04 10:38 UTC by MKodde

The new icons where exported from figma and are a round grey badge with kind of the same logo in them. Additionally a drop shadow is part of the SVG. 

The drop shadow looks best when the SVG is rendered a bit larger. I considered removing the SVG drop shadow and let CSS render a box shadow. But this was an idiot idea. As the box part of the box layout caused a square shadow around the round logo..

![Screenshot from 2020-11-04 11-14-53](https://user-images.githubusercontent.com/28252948/98101260-3e0c8b00-1e92-11eb-8222-b6b83e59be1f.png)

2020-11-10 11:19 UTC, Badlapje requested changes
A small accessibility tweak.  Other than that it looks good.

2020-11-10 11:19 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/shield_key.svg
> +<svg width="50" height="50" focusable="false" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
The svg should need an empty title element to indicate the alt text.  Same for the other one.  Then on the outside svg element add a aria-labelledby attribute containing the id of the title tag.  

`<title id="some_id_for_the_svg"></title>`

2020-11-10 14:27 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/shield_key.svg
> +<svg width="50" height="50" focusable="false" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
I tried this, but to no avail. The HTML check in the A11y spec complains about `no-missing-referencesElement references missing id "fifo-title"`. 

Why is it important to have this aria-labelledby solution in place? Wouldn't setting a simple empty label/title on the svg not have the same effect?

2020-11-11 09:07 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/shield_key.svg
> +<svg width="50" height="50" focusable="false" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
A label wouldn't, but an empty title by itself should suffice.  Some screenreaders however aren't build sturdy enough and require some more nuts and bolts.  If a11y spec keeps complaining about it though, then best to do it without the id/aria-labelledby.  I guess the automatic inspection has caught up with bad implementation from screenreaders now.

2020-11-16 09:57 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/shield_key.svg
> +<svg width="50" height="50" focusable="false" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
Will give your other suggestion a try. 

But maybe we should not comply to a poor inspection when the solution you proposed is the actual best practice.. It's up to you to decide. For now I'm going to set the empty title.

2020-11-16 13:41 UTC, Badlapje requested changes
Other than the title element looking good :-)

2020-11-16 13:41 UTC, Badlapje commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/file_info.svg
> +<svg title="" width="50" height="50" focusable="false" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
this shouldn't be an attribute but a title element.

so <title></title> as the first child element within the svg-element

2020-11-17 08:45 UTC, MKodde commented on theme/base/templates/modules/Authentication/View/Proxy/Partials/Consent/SVG/file_info.svg
> +<svg title="" width="50" height="50" focusable="false" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
Driemaal is scheepsrecht

2020-11-17 08:54 UTC, merged