Fix undefined index error
OpenConext/OpenConext-engineblock pull request #966
Opened 2020-11-04 17:15 UTC by tvdijen

Oct 30 19:14:34 sv2010010 EBLOG-FIN[21532]: [2020-10-30 19:14:34] app.ERROR: Undefined index: idp [/apps/installation/OpenConext-engineblock/engine.broker.fin.rijksdienst.nl/OpenConext-engineblock-6.3.6/library/EngineBlock/Corto/Module/Service/ContinueToIdp.php:67]

This should never happen in the first place, but it could happen if a session is lost..

2020-11-04 19:20 UTC, thijskh commented
Thanks! The code change looks good to me. The build fails (seems unrelated, but I'd prefer that we have a passing build when merging things to master)

2020-11-05 07:34 UTC, MKodde reviewed
@thijskh we are running into the Composer 2 incompatibility here. 

What do you prefer?

1. Downgrade to composer 1.
2. Provide composer 2 compatibility.

I recon 1 is the most pragmatic an least time consuming option at this point..

2020-11-05 07:34 UTC, MKodde commented on library/EngineBlock/Corto/Module/Service/ContinueToIdp.php
> +        if (!isset($selectedIdp)) {
I have one small nitpick. And thats regarding the use of `isset`. I think using the old construction of `if (!$selectedIdP) {` makes more sense semantically.  But feel free to leave as is!

Thanks @tvdijen, I love these defense in depth kind of contributions!

2020-11-05 08:06 UTC, tvdijen commented on library/EngineBlock/Corto/Module/Service/ContinueToIdp.php
> +        if (!isset($selectedIdp)) {
But that's a loose comparision and we shouldn't want that...  `!== null` be better then?

2020-11-05 11:08 UTC, MKodde commented on library/EngineBlock/Corto/Module/Service/ContinueToIdp.php
> +        if (!isset($selectedIdp)) {
Agreed :+1:  `!== null` or even using the `is_null` function sounds like a plan. Again, your proposal is fine with me. Just venting my personal preferences here.

2020-11-05 11:14 UTC, tvdijen commented on library/EngineBlock/Corto/Module/Service/ContinueToIdp.php
> +        if (!isset($selectedIdp)) {
I took care of it..

2020-11-05 17:39 UTC, thijskh commented
1 seems good

2020-11-05 17:44 UTC, thijskh commented
@tvdijen Build should be fixed in master, can you rebase so we’re sure the build passes?

2020-11-05 19:46 UTC, thijskh requested changes

2020-11-05 19:46 UTC, thijskh commented on library/EngineBlock/Corto/Module/Service/ContinueToIdp.php
> +        if ($selectedIdp !== null) {
Probably should be `=== null`?

2020-11-06 06:42 UTC, thijskh approved these changes

2020-11-06 08:08 UTC, merged