Validate required fields
OpenConext/OpenConext-engineblock pull request #975
Opened 2020-11-18 10:03 UTC by MKodde

Tests are not provided to prevent issues with #970 

When that PR is merged, tests can be added to this PR.

2020-11-18 13:49 UTC, MKodde commented
@Badlapje When you've got a lost moment, would you be so kind to look into this strange behavior? 

The failing Cypress tests seem to break on the malfunctioning `Request access` button. This button no longer reacts to `enter` presses. I debugged this to some extent and think this has to do with the construction below. 

https://github.com/OpenConext/OpenConext-engineblock/blob/21b687c59f5cf3f240ce1ef0ffc2fb8609d67098/theme/base/javascripts/wayf/noAccess/attachClickHandlerToRequestButton.js#L17-L32

Do you recal how/why this construction was created? And do you have a clue on how to fix this? I'm hitting a wal here.

2020-11-18 15:08 UTC, Badlapje commented
> 
> 
> @Badlapje When you've got a lost moment, would you be so kind to look into this strange behavior?
> 
> The failing Cypress tests seem to break on the malfunctioning `Request access` button. This button no longer reacts to `enter` presses. I debugged this to some extent and think this has to do with the construction below.
> 
> https://github.com/OpenConext/OpenConext-engineblock/blob/21b687c59f5cf3f240ce1ef0ffc2fb8609d67098/theme/base/javascripts/wayf/noAccess/attachClickHandlerToRequestButton.js#L17-L32
> 
> Do you recal how/why this construction was created? And do you have a clue on how to fix this? I'm stuck.

It was created because else the clickhandler is added more than once.  With that construction it should only be added once.

I'll take a look in an hour or so to see if i can fix it.

2020-11-19 10:29 UTC, Badlapje commented on theme/base/javascripts/wayf/noAccess/validation.js
> +  if (!formData.has('name') || formData.get('name').trim() === '') {
this could be extracted into a function called something like `notAnEmptyField(formData, formName)`.

Would improve readability & make code a bit DRYer as line 20 is the exact same, save for the name of the field.

2020-11-19 10:31 UTC, Badlapje commented on theme/base/javascripts/wayf/noAccess/validation.js
> +  if (!formData.has('name') || formData.get('name').trim() === '') {
could even make it into a method called `validateFieldNotEmpty(formData, formName)` and have it return a boolean.  

`valid = validateFieldNotEmpty(...);`

2020-11-19 10:34 UTC, Badlapje commented on theme/base/javascripts/wayf/noAccess/validation.js
> +  const errorMessage = document.querySelector(`input[name="${elementName}"]`).parentElement.getElementsByClassName('form__error')[0];
you could simplify this query by adding a data-forField (name up to you) to the html of the form__error element.  That'd allow you to select it directly rather than going the long way round.

Probably not that important, but would be a bit more performant.

2020-11-19 10:36 UTC, Badlapje commented on theme/base/javascripts/wayf/noAccess/validation.js
> +    errorMessage.style.display = 'block';
You could show and hide it by adding / removing the hidden attribute.  Not that important, but i try to avoid inline css like this whenever possible (same for the hideValidationMessage function).

2020-11-19 10:37 UTC, Badlapje requested changes
I'd make some smaller changes.  Otherwise nice work!  

If you disagree, feel free to merge ;-)  Nothing big in what I'd change.

2020-11-19 12:04 UTC, MKodde commented on theme/base/javascripts/wayf/noAccess/validation.js
> +  if (!formData.has('name') || formData.get('name').trim() === '') {
Great suggestion! Going to incorporate this right away.

2020-11-19 13:13 UTC, MKodde commented on theme/base/javascripts/wayf/noAccess/validation.js
> +  const errorMessage = document.querySelector(`input[name="${elementName}"]`).parentElement.getElementsByClassName('form__error')[0];
Good point, fixed that up

2020-11-19 13:13 UTC, MKodde commented on theme/base/javascripts/wayf/noAccess/validation.js
> +    errorMessage.style.display = 'block';
Thanks for the suggestion, reworked this to make this work with the hidden class.

2020-11-19 13:14 UTC, MKodde commented on theme/base/javascripts/wayf/handleEnter.js
> -        toggleFormFieldsAndButton(); break;
:wastebasket: FTW!

2020-11-19 13:55 UTC, Badlapje approved these changes
Looking great, nice work!

2020-11-23 07:41 UTC, MKodde commented
@Badlapje I suspect removing the handler did cause a behavioral change. As demonstrated by the failing WAYF keyboard tests. Could you verify that, and maybe fix it :grin:

2020-11-23 14:37 UTC, MKodde commented
Lets move ahead with this!

2020-11-23 14:38 UTC, merged